name: Publish
on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and Publish Project
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Setup Yarn
        run: corepack enable

      - name: Configure Yarn auth
        run: |
          yarn config set npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken "$NODE_AUTH_TOKEN"

      - name: Install Node.js dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn prepare

      - name: Publish project
        run: yarn npm publish --access public
